### ISSUE TITLE
No run.py found

### ISSUE THREAD

**Issue by daakong** [vincent341/S-ANS#1]
Thanks for your contribution. I cannot find the script "run.py". I am wondering if the key script "run.py" is contained in this repository. I would appreciate it a lot if you can share the script. Best wishes.

**Comment by vincent341** [comment]
> Thanks for your contribution. I cannot find the script "run.py". I am wondering if the key script "run.py" is contained in this repository. I would appreciate it a lot if you can share the script. Best wishes.

Please follow the listed install instructions to run the program. Because our work was built on top of [Occuanpy Anticipation](https://github.com/facebookresearch/OccupancyAnticipation), please first download and install the implementation of [Occuanpy Anticipation](https://github.com/facebookresearch/OccupancyAnticipation) as required.

**Comment by daakong** [comment]
Thanks!
